#!/bin/bash
echo $(python3 -c "w=str.maketrans'water','01234');s=str.maketrans('stir.','01234');r=str.maketrans('01234567','bestchol');print((str(int('$WATER'.translate(w),5)+int('$STIR'.translate(s),5)).translate(r))" )
