#!/bin/bash
printf "%s\n" $(python3 -c "a=int(\"$WATER\".translate(str.maketrans(\"water\",\"01234\")),5)+int(\"$STIR\".translate(str.maketrans(\"stir.\",\"01234\")),5);r=\"\"\nexec(\"while a:\\n r=\\\"bestchol\\\"[a%8]+r\\n a//=8\")\nprint(r)")
